### PR TITLE
Add HTC 10 (pme)

### PR DESCRIPTION
**Pull request by vanyasem**
Generated with `cat /var/lib/lxc/android/rootfs/ueventd*.rc|grep ^/dev|sed -e 's/^\/dev\///'|awk '{printf "ACTION==\"add\", KERNEL==\"%s\", OWNER=\"%s\", GROUP=\"%s\", MODE=\"%s\"\n",$1,$3,$4,$2}' | sed -e 's/\r//' >/usr/lib/lxc-android-config/70-pme.rules`

### CODE REVIEW

**Comment by vanyasem** [comment]
@UniversalSuperBox why has the CI failed?

**Comment by UniversalSuperBox** [comment]
Looks like you pushed against the `master` branch whereas we're using `xenial`. Marius just changed your PR's target and changed the default branch. Luckily it was just packaging that failed rather than building. I'd be very concerned if the binary itself failed.

**Comment by vanyasem** [comment]
Makes sense, sorry. It looks like the CI has failed again. Is there anything I have to do in order to trigger a re-build?

**Comment by UniversalSuperBox** [comment]
You can reopen this PR against xenial (Jenkins is still using the file from master), or we can trust that this actually works. @mariogrip, do you trust this man?

**Comment by mariogrip** [comment]
Yeah what can go wrong

**Pull request merged**
